#!/usr/bin/env python3
"""Convert an image into a Marlin custom bootscreen header (config/_Bootscreen.h).

Target hardware: 128x64 monochrome DOGM display (CR10_STOCKDISPLAY).

The image is composited over black (transparent -> unlit), converted to
grayscale, scaled to fit within the panel while preserving aspect ratio, and
centered on a 128x64 canvas. Pixels brighter than --threshold become lit.

Usage:
    python scripts/make_bootscreen.py images/digital.png
    python scripts/make_bootscreen.py images/digital.png --threshold 110 --invert
"""
import argparse

from PIL import Image


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("image", help="source image (any format Pillow can read)")
    ap.add_argument("--out", default="config/_Bootscreen.h")
    ap.add_argument("--width", type=int, default=128)
    ap.add_argument("--height", type=int, default=64)
    ap.add_argument("--threshold", type=int, default=128,
                    help="luminance (0-255) at/above which a pixel is lit")
    ap.add_argument("--invert", action="store_true",
                    help="flip lit/unlit in the packed data")
    ap.add_argument("--timeout", type=int, default=2500,
                    help="ms to show the bootscreen")
    args = ap.parse_args()

    W, H = args.width, args.height

    src = Image.open(args.image).convert("RGBA")
    # Composite over black so transparent areas render as unlit pixels.
    flat = Image.alpha_composite(Image.new("RGBA", src.size, (0, 0, 0, 255)),
                                 src).convert("L")

    # Fit within WxH (preserve aspect), then center on a black canvas.
    fitted = flat.copy()
    fitted.thumbnail((W, H), Image.LANCZOS)
    canvas = Image.new("L", (W, H), 0)
    canvas.paste(fitted, ((W - fitted.width) // 2, (H - fitted.height) // 2))

    px = canvas.load()
    bytes_per_row = (W + 7) // 8
    data = bytearray()
    for y in range(H):
        for bx in range(bytes_per_row):
            b = 0
            for bit in range(8):
                x = bx * 8 + bit
                lit = x < W and px[x, y] >= args.threshold
                if args.invert:
                    lit = not lit
                if lit:
                    b |= 1 << (7 - bit)
            data.append(b)

    out = []
    out.append("#pragma once")
    out.append("")
    out.append("// Generated by scripts/make_bootscreen.py - do not edit by hand.")
    out.append(f"// Source: {args.image} ({W}x{H}, threshold={args.threshold}, "
               f"invert={args.invert})")
    out.append("")
    out.append(f"#define CUSTOM_BOOTSCREEN_TIMEOUT {args.timeout}")
    out.append(f"#define CUSTOM_BOOTSCREEN_BMPWIDTH {W}")
    out.append("")
    out.append("const unsigned char custom_start_bmp[] PROGMEM = {")
    for y in range(H):
        row = data[y * bytes_per_row:(y + 1) * bytes_per_row]
        out.append("  " + ", ".join(f"0x{b:02X}" for b in row) + ",")
    out.append("};")
    out.append("")

    with open(args.out, "w", newline="\n") as f:
        f.write("\n".join(out))
    print(f"Wrote {args.out}: {W}x{H}, {len(data)} bytes "
          f"(threshold={args.threshold}, invert={args.invert})")


if __name__ == "__main__":
    main()
